# Generated by Django 4.1.4 on 2022-12-12 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EstacaoTrabalho',
            fields=[
                ('identificador', models.AutoField(max_length=100, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=20)),
                ('modelo', models.CharField(max_length=12)),
                ('serial', models.CharField(max_length=20)),
                ('setor', models.CharField(max_length=10)),
            ],
        ),
    ]
