# Generated by Django 4.1.4 on 2022-12-12 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estacao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estacaotrabalho',
            name='identificador',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
